### ISSUE TITLE
A singleton should be instantiable?

### ISSUE THREAD

**Issue by raphaelboukara** [sahariko/singleton#6]
![image](https://user-images.githubusercontent.com/6442236/48601911-24f33280-e97a-11e8-816a-582f5a869924.png)
From what I understand a singleton should be instantiable almost one time. I would expect something like:
```
class Single extends Singleton {}

const a = new Single();
const b = new Single();

a === b // true
```
WDYT?

**Comment by sahariko** [comment]
You're correct, a singleton is instantiated once and only once, when the first call to `Singleton.getInstance()` or `Singleton.instance` is made.

In a classic singleton pattern, the class's constructor is made private, and the responsibility for creating the instance is passed to the class itself.

This also enforces the concept of a single instance. Consider the following:

```js
// class Single

class Single extends Singleton {
    constructor(id) {
        this.id = id;
    }
}

// Module A

const a = new Single(1);

// Module B

const b = new Single(2);
```

What would you expect the singleton instance's `id` would be?
It would depend on the execution order, of course, thus conflicting with the pattern.

**Comment by sahariko** [comment]
Closing this issue for now.
@raphaelboukara if you still feel this should be discussed, please feel free to reopen 🙂
